### ISSUE TITLE
problem with SetMass.PathLib in MetaboAnalystR

### ISSUE THREAD

**Issue by mmencuccini** [jsychong/MetaboAnalystR#1]
Hi
I am having problem running the above command in MetaboAnalystR. I have run the same file successfully over the internet.
My installation of MetaboAnalystR was done using the recommended function metanr_packages. Packages installed fine via R or BioConductor, although several warnings appeared:
* checking for file 'C:\Users\Maurizio Mencuccini\AppData\Local\Temp\RtmpOQrMUz\devtoolse2813764b4a\xia-lab-MetaboAnalystR-26ee5bb/DESCRIPTION' ... OK
* preparing 'MetaboAnalystR':
* checking DESCRIPTION meta-information ... OK
Warning: C:/Users/Maurizio Mencuccini/AppData/Local/Temp/RtmpgFG46u/Rbuild33686d902db/MetaboAnalystR/man/ComputeHighLow.Rd:6: unexpected section header '\usage'
Warning: C:/Users/Maurizio Mencuccini/AppData/Local/Temp/RtmpgFG46u/Rbuild33686d902db/MetaboAnalystR/man/ComputeHighLow.Rd:9: unexpected section header '\description'
Warning: C:/Users/Maurizio Mencuccini/AppData/Local/Temp/RtmpgFG46u/Rbuild33686d902db/MetaboAnalystR/man/ComputeHighLow.Rd:12: unexpected section header '\author'
Warning: C:/Users/Maurizio Mencuccini/AppData/Local/Temp/RtmpgFG46u/Rbuild33686d902db/MetaboAnalystR/man/ComputeHighLow.Rd:17: unexpected END_OF_INPUT '
'
Warning: C:/Users/Maurizio Mencuccini/AppData/Local/Temp/RtmpgFG46u/Rbuild33686d902db/MetaboAnalystR/man/Perform.UnivROC.Rd:23: unknown macro '\item'
Warning: C:/Users/Maurizio Mencuccini/AppData/Local/Temp/RtmpgFG46u/Rbuild33686d902db/MetaboAnalystR/man/Perform.UnivROC.Rd:25: unknown macro '\item'
Warning: C:/Users/Maurizio Mencuccini/AppData/Local/Temp/RtmpgFG46u/Rbuild33686d902db/MetaboAnalystR/man/Perform.UnivROC.Rd:28: unknown macro '\item'
Warning: C:/Users/Maurizio Mencuccini/AppData/Local/Temp/RtmpgFG46u/Rbuild33686d902db/MetaboAnalystR/man/Perform.UnivROC.Rd:30: unknown macro '\item'
Warning: C:/Users/Maurizio Mencuccini/AppData/Local/Temp/RtmpgFG46u/Rbuild33686d902db/MetaboAnalystR/man/Perform.UnivROC.Rd:33: unknown macro '\item'
Warning: C:/Users/Maurizio Mencuccini/AppData/Local/Temp/RtmpgFG46u/Rbuild33686d902db/MetaboAnalystR/man/Perform.UnivROC.Rd:35: unexpected section header '\description'
Warning: C:/Users/Maurizio Mencuccini/AppData/Local/Temp/RtmpgFG46u/Rbuild33686d902db/MetaboAnalystR/man/Perform.UnivROC.Rd:38: unexpected section header '\author'
Warning: C:/Users/Maurizio Mencuccini/AppData/Local/Temp/RtmpgFG46u/Rbuild33686d902db/MetaboAnalystR/man/Perform.UnivROC.Rd:43: unexpected END_OF_INPUT '
'
Warning: C:/Users/Maurizio Mencuccini/AppData/Local/Temp/RtmpgFG46u/Rbuild33686d902db/MetaboAnalystR/man/PlotImpVars.Rd:6: unexpected section header '\usage'
Warning: C:/Users/Maurizio Mencuccini/AppData/Local/Temp/RtmpgFG46u/Rbuild33686d902db/MetaboAnalystR/man/PlotImpVars.Rd:9: unexpected section header '\arguments'
Warning: C:/Users/Maurizio Mencuccini/AppData/Local/Temp/RtmpgFG46u/Rbuild33686d902db/MetaboAnalystR/man/PlotImpVars.Rd:10: unknown macro '\item'
Warning: C:/Users/Maurizio Mencuccini/AppData/Local/Temp/RtmpgFG46u/Rbuild33686d902db/MetaboAnalystR/man/PlotImpVars.Rd:12: unknown macro '\item'
Warning: C:/Users/Maurizio Mencuccini/AppData/Local/Temp/RtmpgFG46u/Rbuild33686d902db/MetaboAnalystR/man/PlotImpVars.Rd:14: unknown macro '\item'
Warning: C:/Users/Maurizio Mencuccini/AppData/Local/Temp/RtmpgFG46u/Rbuild33686d902db/MetaboAnalystR/man/PlotImpVars.Rd:16: unknown macro '\item'
Warning: C:/Users/Maurizio Mencuccini/AppData/Local/Temp/RtmpgFG46u/Rbuild33686d902db/MetaboAnalystR/man/PlotImpVars.Rd:19: unknown macro '\item'
Warning: C:/Users/Maurizio Mencuccini/AppData/Local/Temp/RtmpgFG46u/Rbuild33686d902db/MetaboAnalystR/man/PlotImpVars.Rd:21: unknown macro '\item'
Warning: C:/Users/Maurizio Mencuccini/AppData/Local/Temp/RtmpgFG46u/Rbuild33686d902db/MetaboAnalystR/man/PlotImpVars.Rd:24: unknown macro '\item'
Warning: C:/Users/Maurizio Mencuccini/AppData/Local/Temp/RtmpgFG46u/Rbuild33686d902db/MetaboAnalystR/man/PlotImpVars.Rd:26: unexpected section header '\description'
Warning: C:/Users/Maurizio Mencuccini/AppData/Local/Temp/RtmpgFG46u/Rbuild33686d902db/MetaboAnalystR/man/PlotImpVars.Rd:29: unexpected section header '\author'
Warning: C:/Users/Maurizio Mencuccini/AppData/Local/Temp/RtmpgFG46u/Rbuild33686d902db/MetaboAnalystR/man/PlotImpVars.Rd:34: unexpected END_OF_INPUT '
'
Warning: C:/Users/Maurizio Mencuccini/AppData/Local/Temp/RtmpgFG46u/Rbuild33686d902db/MetaboAnalystR/man/PlotPCA2DScore.Rd:28: unknown macro '\item'
Warning: C:/Users/Maurizio Mencuccini/AppData/Local/Temp/RtmpgFG46u/Rbuild33686d902db/MetaboAnalystR/man/PlotPCA2DScore.Rd:30: unknown macro '\item'
Warning: C:/Users/Maurizio Mencuccini/AppData/Local/Temp/RtmpgFG46u/Rbuild33686d902db/MetaboAnalystR/man/PlotPCA2DScore.Rd:32: unexpected section header '\description'
Warning: C:/Users/Maurizio Mencuccini/AppData/Local/Temp/RtmpgFG46u/Rbuild33686d902db/MetaboAnalystR/man/PlotPCA2DScore.Rd:35: unexpected section header '\author'
Warning: C:/Users/Maurizio Mencuccini/AppData/Local/Temp/RtmpgFG46u/Rbuild33686d902db/MetaboAnalystR/man/PlotPCA2DScore.Rd:40: unexpected END_OF_INPUT '
'
Warning: C:/Users/Maurizio Mencuccini/AppData/Local/Temp/RtmpgFG46u/Rbuild33686d902db/MetaboAnalystR/man/RemoveMissingPercent.Rd:14: unexpected section header '\description'
Warning: C:/Users/Maurizio Mencuccini/AppData/Local/Temp/RtmpgFG46u/Rbuild33686d902db/MetaboAnalystR/man/RemoveMissingPercent.Rd:17: unexpected section header '\author'
Warning: C:/Users/Maurizio Mencuccini/AppData/Local/Temp/RtmpgFG46u/Rbuild33686d902db/MetaboAnalystR/man/RemoveMissingPercent.Rd:22: unexpected END_OF_INPUT '
'
* installing the package to build vignettes
* creating vignettes ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building 'MetaboAnalystR_0.0.0.9000.tar.gz'
** building package indices
** installing vignettes
** testing if installed package can be loaded
............................................................................................
*** arch - i386
*** arch - x64
* DONE (MetaboAnalystR)
In R CMD INSTALL

When I run the command, the following error appears:
> mSet <- SetMass.PathLib(mSet, "ath_kegg")
Error in gzfile(file, "rb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file 'C:/Users/...../Documents/Desktop/mummichog_libraries/kegg_pathways/ath_kegg.rds', probable reason 'No such file or directory'
The path up to Documents seems sensible if it is looking for R libraries; however the directory Desktop does not exist within Document, hence the file is not found. I have also manually looked for the mummichog_libraries directory and, as far as I can tell it is nowhere to be found.
I have uninstalled both RStudio and R_3.4.3, including all the libraries, to no avail.

> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Cairo_1.5-9               MetaboAnalystR_0.0.0.9000 devtools_1.13.4           BiocInstaller_1.28.0     

loaded via a namespace (and not attached):
 [1] httr_1.3.1     compiler_3.4.3 R6_2.2.2       tools_3.4.3    withr_2.1.1    curl_3.1       yaml_2.1.16    memoise_1.1.0  knitr_1.19     git2r_0.21.0   digest_0.6.15

**Comment by jsychong** [comment]
Hi,

Thank you for pointing this out, the path to download the necessary files have been fixed. Please re-download the updated R package.

Cheers,
Jasmine

**Comment by mmencuccini** [comment]
many thanks.
It now moves one step forward and proceeds to download the ath_kegg file. Having completed the downloading, it gives a new error message:
'> mSet <- SetMass.PathLib(mSet, "ath_kegg")
Error in readRDS(filenm) : error reading from connection
In addition: Warning message:
In readRDS(filenm) : invalid or incomplete compressed data'
I have restarted RStudio without success.
I then mistakenly run the following line as well:
> mSet <- PerformMummichog(mSet, "fisher", "gamma")
which produces the following error.
Error in PerformMummichog(mSet, "fisher", "gamma") : 
  could not find function "PerformMummichog"
It is perhaps because mSet was not modified, but I mention it since it seems to depend on the function rather than the object.
many thanks for the help so far

**Comment by jsychong** [comment]
Yes, thanks, the "PerformMummichog" function wasn't exported - it is now. Also, I can't re-produce your error, but from some digging I added some code when downloading the file, hopefully this fixes the issue on your end. The R package has been updated.

**Comment by mmencuccini** [comment]
Hi there,
on the SetMass.PathLib(mSet, "ath_kegg") command,
 I still get the same error unfortunately. I still also do not see the PerformMummichog function.
I have re-installed from the *1.0.0.5.tar.gz file. is that the correct file to use?

**Comment by jsychong** [comment]
Hi,
Please use the new 1.0.0.6 file, the last file didn't have a documentation update which has been fixed! Also, please use remove.packages("MetaboAnalystR") to delete the previous MetR, and then re-install with the new file. PerformMummichog should now be viewable. As for the previous issue, what is your R version? Mine is R version 3.4.1 (2017-06-30), which if yours is older, could be the source of the issue.

**Comment by mmencuccini** [comment]
I apologise, I must appear rather incompetent. 
I am running R version 3.4.3 (2017-11-30), so that is not a problem. 
I have uninstalled as suggested and uploaded the correct tar file (1.0.0.6). However, if I run:
> packageDescription("MetaboAnalystR")$Version
[1] "0.0.0.9000"
?? I have repeated this twice to make sure. I am obviously missing something basic. 
Interestingly however, if I run the PerformMummichog command, it now states:
Error in LoadMummichogLib(mSetObj) : 
  could not find function "LoadMummichogLib"
ie, I have moved a step further. I am rather confused.

**Comment by mmencuccini** [comment]
As an additional clarification on the message above, I have double checked the installation directory of the R library and it is installing and loading from the right place.

**Comment by mmencuccini** [comment]
Finally spotted my mistake in loading the package. Still get the old description of the package version ("0.0.0.9000") when I run packageVersion("MetaboAnalystR") and all the warnings at installation, but the program now runs fine. It has been very useful. A final comment I have is that I am very pleased with how mummichog ran. I would certainly encourage you to include the gamma test of the network modules as per original Li et al (2013) paper, to complement pathway analysis. Given your expanded list of model organisms from which to draw, your packages can be highly useful to many people interested in untargeted metabolomics. Many thanks for your help so far.

**Comment by jsychong** [comment]
That's great! I'm glad it worked out and you enjoyed using the mummichog. We are definitely considering expanding the code for including network modules, it may be in an upcoming update. Cheers!
